name: Scrape README.md
run-name: 🚀 Update README.md

on:
  push:
    branches:
      - test
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  scrape-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install -r .github/workflows/requirements.txt
      - run: python .github/workflows/scraper.py

      - name: Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":octocat: Update README.md"