name: Update submodules
run-name: 🚀 Update README.md

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:

      - name: 📦 Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: ⬆️ Update submodules
        run: git submodule update --remote

      - name: ✨ Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":arrow_up: Upgrade submodules"