on:
  workflow_call:
    inputs:
      path-filter:
        description: 'Path containing the source code'
        required: true
        type: string

jobs:
  update-documentation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            ${{ inputs.path-filter }}
          separator: " "

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r leowajda/eureka-scraper/.github/workflows/requirements.txt@master
      - run: python .github/workflows/script.py ${{ github.event.repository.url }} ${{ steps.changed-files.outputs.all_changed_files }}


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":octocat: Update /docs and README.md"